name: 2Lands2ConqueredCore(Fork Of LEF)
version: 0.0.1
main: org.l2x9.l2x9core.Main
authors: [ 254n_m, Leeewith3Es ] [Remade by Lvoring]
description:  ${project.description}
website: https://www.xera.ca
softdepend:
  - SalC1Dupe
commands:
  say:
    description: e
  open:
    description: e
  crash:
    description: e
  speed:
    description: e
  uuid:
    description: e
  uptime:
    description: e
  lef:
    description: e
  discord:
    description: e
  world:
    description: e
  help:
    description: e
  spawn:
    description: e
  toggleconnectionmessages:
    description: Toggles on / off connection messages for the sender of the command
    aliases:
      - tc
      - toggleconnection